name = "rejseplanen"
workers_dev = true
compatibility_date = "2022-01-20"
main = "build/worker/shim.mjs"

[vars]
WORKERS_RS_VERSION = "0.0.15"
REJSEPLANEN_URL = "http://example.com"

[build]
command = "cargo install -q worker-build && worker-build --release" # required

[[rules]]
globs = [ "**/*.wasm" ]
type = "CompiledWasm"

# read more about configuring your Worker via wrangler.toml at:
# https://developers.cloudflare.com/workers/cli-wrangler/configuration
