name: graphs

channels:
    - conda-forge

dependencies:
    - python=3.10
    - geopandas
    - matplotlib
    - numpy<1.24
    - pandas
    - plotly
    - graph-tool
    - pydeck
    - h3-py
    - pip
    - pip:
        - pyrosm
        - pyproj
        - shapely==1.8.5
        - tqdm
        - polars
        - gtfs_kit
        - h3ronpy
        - pyarrow
        - seaborn
        - lets_plot
        - contextily
        - osmnx