[package]
name = "poi-extractor"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0"

gdal = "0.14.0"
h3o = "0.3.0"
